version: '3.7'

networks:
  proxy_network:
    driver: bridge

volumes:
  acme-certs:

services:

  traefik:
    image: traefik:v2.10
    container_name: "reverse_proxy"
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=base_proxy_network"
      - "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # - "--certificatesresolvers.myresolver.acme.email=juan11iguel@gmail.com"
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    networks:
        - proxy_network
    ports:
      - "80:80"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - "acme-certs:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.http.routers.traefik.service=api@internal"

      # Traefik dashboard as subpath 
      # I don't think it's possible at the moment. See https://github.com/containous/traefik/issues/5374
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=PathPrefix(`/traefik`)"
      # - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.middlewares=traefik@docker"
      - "traefik.http.middlewares.traefik.stripprefix.prefixes=/traefik"


      # - "traefik.http.routers.traefik.middlewares=traefik-auth"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$8EVjn/nj$$GiLUZqcbueTFeD23SuB6x0" # username: admin, password: admin

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=( Host(`whoami.localhost`) || PathPrefix(`/whoami`) )"
      # - "traefik.http.routers.whoami.tls.certresolver=myresolver"
