version: '3'

networks:
    base_proxy_network:
        external: true

services:
  wascop_app:
    image: ghcr.io/juan11iguel/solhycool_optimization:latest
    container_name: wascop_app
    depends_on:
      - redis

    command:
      # Run a command that will make the container stay alive
      # sh -c "while true; do sleep 10; done;"
      # sh -c "gunicorn --env SCRIPT_NAME=/solhycool --env CONF_FILE=$$CONF_FILE --env CACHE_TYPE=$$CACHE_TYPE --env REDIS_PORT=$$REDIS_PORT -b 0.0.0.0:8000 run:server"
      sh -c "gunicorn --env CONF_FILE=$$CONF_FILE --env CACHE_TYPE=$$CACHE_TYPE --env REDIS_PORT=$$REDIS_PORT -b 0.0.0.0:8000 run:server"
    
    working_dir: /wascop_app
    volumes:
      - ../assets/wascop_app:/wascop_app/assets/
      - ../configuration_files:/wascop_app/configuration_files/
    
    ports:
      - 8070:8000
    environment:
      CONF_FILE: configuration_files/wascop_app.hjson
      CACHE_TYPE: "redis"
      REDIS_PORT: 6379

    networks:
      - base_proxy_network
    labels:
      # Whatchtower
      - "com.centurylinklabs.watchtower.enable=true"

      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.wascop_app.rule=PathPrefix(`/solhycool`)"
      # - "traefik.http.routers.wascop_app.tls.certresolver=myresolver"
      - "traefik.http.services.wascop_app.loadbalancer.server.port=8000"
      # - "traefik.http.routers.wascop_app.middlewares=wascop_app@docker"
      # - "traefik.http.middlewares.wascop_app.stripprefix.prefixes=/solhycool"

  # Container that everytime detects a change in optimization_V1 folder, it will generate an updated
  # results.json file and create the new diagrams
  wascop_results_updater:
    image: ghcr.io/juan11iguel/solhycool_optimization:latest 
    container_name: wascop_results_updater

    working_dir: /wascop_app

    command: python generate_results.py --results_folder_path "assets/optimization_V1" --src_diagram_path "assets/optimization_V1/diagrams/aux/WASCOP-Resultados JJAA.svg" --dark_variant true

    volumes:
      - ../assets/wascop_app:/wascop_app/assets/
      - ../configuration_files:/wascop_app/configuration_files/
      
    environment:
      CONF_FILE: configuration_files/wascop_app.hjson

    labels:
      # Whatchtower
      - "com.centurylinklabs.watchtower.enable=true"

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - base_proxy_network
    # ports: 
    #   - 6379:6379
    
