version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container-name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30 --label-enable true
